springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.tsh.starter.befw   # 본인 패키지 경로

spring:
  jpa:
    properties:
      org.hibernate.envers:
        audit_table_suffix: _HIST     # 이력 테이블명 뒤에 _HISTORY 붙임


application:
  group-id: @project.groupId@
  version: @project.version@
  tenant: SITE
  service:
  env: LOCAL
  module:
    name: befw-app
    seq: 1


messaging:
  solace:
    host: localhost
    vpn: default
    login:
      user: admin       # client-username
      pwd: admin        # password
    switch:
      producer: true
      consumer: true
    log:
      level: INFO
    policy:
      connect:
        timeout:
          ms: 1000
        retries:
          count: -1
      reconnect:
        retries:
          count: 1
          wait-ms: 1000
      compression:
        level: 5
      message:
        ack-mode: 1
        delivery-mode: PERSISTENT
        alive:
          interval-ms: 0
          limit: 0
      security:
        ssl:
          enable: SSL
          store:
            trust: C:\
            key: C:\





