-- Flyway Migration: V10__gs_users_and_permissions
-- Source: 01_users_and_permissions.sql
-- Generated: 2026-05-25

-- ============================================================
-- Cira : 사용자 및 권한 관리 (Phase 1)
-- Prefix: GS_ (Global — befw-lib-core 소속)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. GS_USER (사용자 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_USER
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    USER_NM      VARCHAR(100) NOT NULL,
    AVATAR_URL   VARCHAR(500),
    PWD_HASH     VARCHAR(255) NOT NULL,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    -- BasicAudit
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_USER PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_USER_EMAIL UNIQUE (EMAIL)
);


CREATE INDEX IF NOT EXISTS IDX_GS_USER_USE_STAT ON GS_USER (USE_STAT_CD);

COMMENT ON TABLE GS_USER IS '사용자 기본 정보';
COMMENT ON COLUMN GS_USER.EMAIL IS '이메일 (UK)';
COMMENT ON COLUMN GS_USER.USER_NM IS '사용자명';
COMMENT ON COLUMN GS_USER.AVATAR_URL IS '프로필 이미지 URL';
COMMENT ON COLUMN GS_USER.PWD_HASH IS '비밀번호 해시';
COMMENT ON COLUMN GS_USER.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_USER.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_USER.TENANT IS '테넌트';
COMMENT ON COLUMN GS_USER.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_USER.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_USER.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_USER.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_USER.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_USER.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_USER.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_USER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_USER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_USER.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. GS_ROLE (역할 정의)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_ROLE
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    ROLE_NM      VARCHAR(50)  NOT NULL,
    DESCR        VARCHAR(255),
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_ROLE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_ROLE_NM UNIQUE (ROLE_NM) -- Admin | Developer | Reporter | Viewer
);

COMMENT ON TABLE GS_ROLE IS '역할 정의';
COMMENT ON COLUMN GS_ROLE.ROLE_NM IS '역할명 (Admin | Developer | Reporter | Viewer)';
COMMENT ON COLUMN GS_ROLE.DESCR IS '역할 설명';
COMMENT ON COLUMN GS_ROLE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_ROLE.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_ROLE.TENANT IS '테넌트';
COMMENT ON COLUMN GS_ROLE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_ROLE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_ROLE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_ROLE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_ROLE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_ROLE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_ROLE.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_ROLE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_ROLE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_ROLE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. GS_USER (사용자 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_USER_ROLE
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    USER_ID      VARCHAR(100) NOT NULL,
    ROLE_ID      VARCHAR(100) NOT NULL,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_USER_ROLE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_GS_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT FK_GS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES GS_ROLE (OBJ_ID)
);


CREATE INDEX IF NOT EXISTS IDX_GS_USER_ROLE_ROLE_ID ON GS_USER_ROLE (ROLE_ID);

COMMENT ON TABLE GS_USER_ROLE IS '사용자-역할 매핑';
COMMENT ON COLUMN GS_USER_ROLE.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT ON COLUMN GS_USER_ROLE.ROLE_ID IS '역할 ID (FK → GS_ROLE)';
COMMENT ON COLUMN GS_USER_ROLE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_USER_ROLE.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_USER_ROLE.TENANT IS '테넌트';
COMMENT ON COLUMN GS_USER_ROLE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_USER_ROLE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_USER_ROLE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_USER_ROLE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_USER_ROLE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_USER_ROLE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_USER_ROLE.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_USER_ROLE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_USER_ROLE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_USER_ROLE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 4. GS_PERMISSION (권한 정의)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_PERMISSION
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    PERM_NM      VARCHAR(100) NOT NULL,
    DESCR        VARCHAR(255),
    RESOURCE     VARCHAR(50)  NOT NULL,  -- issue | project | sprint | board …
    ACTION       VARCHAR(50)  NOT NULL, -- create | read | update | delete
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_PERMISSION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_PERMISSION_NM UNIQUE (PERM_NM)
);


CREATE INDEX IF NOT EXISTS IDX_GS_PERMISSION_RESOURCE ON GS_PERMISSION (RESOURCE);

COMMENT ON TABLE GS_PERMISSION IS '권한 정의';
COMMENT ON COLUMN GS_PERMISSION.PERM_NM IS '권한명 (UK)';
COMMENT ON COLUMN GS_PERMISSION.DESCR IS '권한 설명';
COMMENT ON COLUMN GS_PERMISSION.RESOURCE IS '대상 리소스 (issue | project | sprint | board …)';
COMMENT ON COLUMN GS_PERMISSION.ACTION IS '허용 액션 (create | read | update | delete)';
COMMENT ON COLUMN GS_PERMISSION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_PERMISSION.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_PERMISSION.TENANT IS '테넌트';
COMMENT ON COLUMN GS_PERMISSION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_PERMISSION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_PERMISSION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_PERMISSION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_PERMISSION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_PERMISSION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_PERMISSION.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_PERMISSION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_PERMISSION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_PERMISSION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 5. GS_ROLE (역할 정의)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_ROLE_PERMISSION
(
    OBJ_ID        VARCHAR(100) NOT NULL,
    ROLE_ID       VARCHAR(100) NOT NULL,
    PERMISSION_ID VARCHAR(100) NOT NULL,
    -- BaseModel
    SRV_ID        VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT        VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID      VARCHAR(100) NOT NULL,
    USE_STAT_CD   VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM       VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM        TEXT,
    CREATED_BY    VARCHAR(40),
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY   VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_ROLE_PERMISSION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_GS_ROLE_PERMISSION_ROLE FOREIGN KEY (ROLE_ID) REFERENCES GS_ROLE (OBJ_ID),
    CONSTRAINT FK_GS_ROLE_PERMISSION_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES GS_PERMISSION (OBJ_ID)
);

COMMENT ON TABLE GS_ROLE_PERMISSION IS '역할-권한 매핑';
COMMENT ON COLUMN GS_ROLE_PERMISSION.ROLE_ID IS '역할 ID (FK → GS_ROLE)';
COMMENT ON COLUMN GS_ROLE_PERMISSION.PERMISSION_ID IS '권한 ID (FK → GS_PERMISSION)';
COMMENT ON COLUMN GS_ROLE_PERMISSION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_ROLE_PERMISSION.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_ROLE_PERMISSION.TENANT IS '테넌트';
COMMENT ON COLUMN GS_ROLE_PERMISSION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_ROLE_PERMISSION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_ROLE_PERMISSION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_ROLE_PERMISSION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_ROLE_PERMISSION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_ROLE_PERMISSION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_ROLE_PERMISSION.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_ROLE_PERMISSION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_ROLE_PERMISSION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_ROLE_PERMISSION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 6. GS_GROUP (사용자 그룹)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_GROUP
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    GROUP_NM     VARCHAR(100) NOT NULL,
    DESCR        VARCHAR(255),
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_GROUP PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_GROUP_NM UNIQUE (GROUP_NM)
);

COMMENT ON TABLE GS_GROUP IS '사용자 그룹';
COMMENT ON COLUMN GS_GROUP.GROUP_NM IS '그룹명 (UK)';
COMMENT ON COLUMN GS_GROUP.DESCR IS '그룹 설명';
COMMENT ON COLUMN GS_GROUP.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_GROUP.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_GROUP.TENANT IS '테넌트';
COMMENT ON COLUMN GS_GROUP.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_GROUP.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_GROUP.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_GROUP.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_GROUP.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_GROUP.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_GROUP.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_GROUP.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_GROUP.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_GROUP.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 7. GS_GROUP (사용자 그룹)

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS GS_GROUP_MEMBER
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    GROUP_ID     VARCHAR(100) NOT NULL,
    USER_ID      VARCHAR(100) NOT NULL,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_GS_GROUP_MEMBER PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_GS_GROUP_MEMBER UNIQUE (GROUP_ID, USER_ID),
    CONSTRAINT FK_GS_GROUP_MEMBER_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GS_GROUP (OBJ_ID),
    CONSTRAINT FK_GS_GROUP_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IF NOT EXISTS IDX_GS_GROUP_MEMBER_USER_ID ON GS_GROUP_MEMBER (USER_ID);

COMMENT ON TABLE GS_GROUP_MEMBER IS '그룹 멤버십';
COMMENT ON COLUMN GS_GROUP_MEMBER.GROUP_ID IS '그룹 ID (FK → GS_GROUP)';
COMMENT ON COLUMN GS_GROUP_MEMBER.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT ON COLUMN GS_GROUP_MEMBER.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN GS_GROUP_MEMBER.SRV_ID IS '서비스명';
COMMENT ON COLUMN GS_GROUP_MEMBER.TENANT IS '테넌트';
COMMENT ON COLUMN GS_GROUP_MEMBER.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN GS_GROUP_MEMBER.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN GS_GROUP_MEMBER.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN GS_GROUP_MEMBER.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN GS_GROUP_MEMBER.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN GS_GROUP_MEMBER.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN GS_GROUP_MEMBER.CREATED_BY IS '생성자';
COMMENT ON COLUMN GS_GROUP_MEMBER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN GS_GROUP_MEMBER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN GS_GROUP_MEMBER.MODIFIED_AT IS '수정일시';
